<?php

namespace att\appBundle\Repository;

/**
 * AttConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
