<?php

namespace att\attBundle\Repository;

/**
 * AtworkleaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtworkleaveRepository extends \Doctrine\ORM\EntityRepository
{
}
