<?php

namespace att\employeeBundle\Repository;

/**
 * AtdepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtdepartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
