<?php

namespace att\employeeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AtrestdayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtrestdayRepository extends EntityRepository
{
}
