<?php

namespace att\employeeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AtrestdayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtschemaRepository extends EntityRepository
{
    public function findByAgreementId($agremeent_id){
        
        $qb = $this->createQueryBuilder('s');
        $qb->leftJoin('s.agreement', 'a')
            ->where('a.id = :agreemen_id')
            ->setParameter('agreemen_id', $agremeent_id);
    
        return  $qb->getQuery()->getArrayResult();
        
    }
    
    
    
}
