<?php

namespace att\ctrlaccBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AxtonEmployeesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AxtonEmployeesRepository extends EntityRepository
{
}
