<?php

namespace att\ctrlaccBundle\Repository;

/**
 * DeviceMetadataConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceMetadataConfigurationRepository extends \Doctrine\ORM\EntityRepository
{
}
