<?php

namespace att\ctrlaccBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AttendanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository {    

    public function getLastIdOrginalByDevice(\att\ctrlaccBundle\Entity\Device $device) {

        $qb = $this->createQueryBuilder('e')
                ->select('MAX(e.idoriginal) as id')
                ->where('e.iddevice = :device')
                ->setParameter('device', $device);

        $id = $qb->getQuery()->getSingleResult();

        return $id['id'];
    }

}
