<?php

namespace att\ctrlaccBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FingerpointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FingerpointRepository extends EntityRepository
{
}
