<?php

namespace att\syncBundle\Repository;

/**
 * ExternalDatabaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalDatabaseRepository extends \Doctrine\ORM\EntityRepository
{
}
