<?php

namespace att\syncBundle\Repository;

/**
 * ExternalSystemSequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalSystemSequenceRepository extends \Doctrine\ORM\EntityRepository
{
}
