<?php

namespace att\syncBundle\Repository;

/**
 * ExternalDatabaseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExternalDatabaseTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
